fix RuntimeError & switch to in-memory sqlite
Fixed error with flask_sqlalchemy 2.2 (haven't tested with earlier
versions)

    RuntimeError: application not registered on db instance and no
                  application bound to current context